### ISSUE TITLE
Add "how to use" description

### ISSUE THREAD

**Issue by Unloaded123456** [Abstrat-Technologies/rustedanvil#1]
That is a very useful project but there is no tutorial about how to use it. We need a tutorial for this, for instance: "Unzip the file to your 1.6.4 #965 workspace and run install.bat".  

/Unloaded123456 {UnloadedChunk}

**Comment by arek-kwapis** [comment]
Currently, there isn't a way to use it per se - There's no way to get a working install from what is here currently. We are still in the early development stages.

The goal of this project is to allow the simple installation of Forge 965 for 1.6.4, in the very way you showed an example of - a simple one-step process. To get to there, there's a lot of work that needs to be done, 3 stages in fact. As detailed in the README, they are:

Documentation & Information gathering
Toolset creation
Merge & Finalisation

Currently, we are on the first stage, Documentation & Information gathering, named "Milestone 1". From the README:

`This stage will consist of finding and documenting all the issues currently present within Forge 965 and suggesting fixes to each issue. This includes files it fails to download, broken code, missing items and more. This is the most important step, as without documentation on what the issues are, we can't create tools to fix and repair it.`

You are quite correct that there is no adequate information on how to get started. I'm working on the new documentation just now and I should be able to PR it in over the weekend. The first stage is very complex, probably more than the programming part will be, due to how badly broken 965 is. For that reason I don't think many if any will help me with it, so I'm trying to get it finished ASAP.

Of course, once the whole project is in the last stage, at that point there will be full documentation for everything. We're trying to develop it in such a way that even if things break, even a blind drunk monkey with a sledgehammer and a machine gun can fix it, to stop some other poor soul dedicating over half a year of their life to making it work again!

**Comment by Unloaded123456** [comment]
At least

**Comment by Unloaded123456** [comment]
Sorry, I accidentally closed...

**Comment by Unloaded123456** [comment]
Now fixed... 

In fact, a multi-step tutorial also would be enough, something like this:

* Download X
* Edit Y File
* Run x.exe
* Run y.exe
* Run x.bat
* Open your IDE
* Start to modding!

**Comment by arek-kwapis** [comment]
I would give you exactly that... If I remembered the steps I took 😅

The only reason I know some of the last steps that need to be made (Generating MD5 & SHA1 files & downloading assets) is that I got so fed up of manually doing those tasks that I automated them out of sheer spite. 

Otherwise, this is more or less refreshing my brain on what I did 8 months ago until now by encountering each error again on a fresh install, and using my fixed copy as a "oh, that's what I did to fix it" while writing it down so it can be documented for automation during Milestone 2. As I never did write it down originally. By the time I realised there was people other than me wanting 1.6.4 modding to work it was already too late. I know, I'm really dumb sometimes 😀

**Comment by Unloaded123456** [comment]
Hmm... Legacy Fabric looks like the only hope for making loader mods in version 1.6.4...

**Comment by arek-kwapis** [comment]
Fixed in 169907f2aae643da28f1ca235790fb20c58c891d , 3e1a5272c8fc7be93b93c9b32c7275e58818670c and 69072040842e72d83e0eaa988667aa723ac153e0

**Comment by Unloaded123456** [comment]
That is excellent... Now Forge 1.6.4 is revived and will never die!

**Comment by Unloaded123456** [comment]
One step closer to Forge 1.6.4 modding...
